operator:
  resultsVolume:
    enabled: false
strimzi:
  enabled: false
  zookeeper:
    zooEntrance:
      enabled: false
      zookeeperClient:
        enabled: false
  schemaRegistry:
    enabled: false


kube-prometheus-stack:
  nodeSelector:
    kubernetes.io/hostname: kind-worker4
  grafana:
    nodeSelector:
      kubernetes.io/hostname: kind-worker
  prometheusOperator:
    nodeSelector:
      kubernetes.io/hostname: kind-worker4

prometheus:
  nodeSelector:
    kubernetes.io/hostname: kind-worker4

loki-stack:
  nodeSelector:
    kubernetes.io/hostname: kind-worker
  loki:
    nodeSelector:
      kubernetes.io/hostname: kind-worker

kepler:
  enabled: false
  serviceMonitor:
    namespace: theodolite-stu217492
  extraEnvVars:
    ENABLE_GPU: "false"





operator:
  nodeSelector:
    kubernetes.io/hostname: kind-worker4
  sloChecker:
    lagTrend:
      enabled: false
  theodoliteBenchmarks:
    resourceConfigMaps:
      uc1LoadGenerator: false
      uc1Kstreams: false
      uc1Flink: false
      uc1BeamFlink: false
      uc1BeamSamza: false
      uc2LoadGenerator: false
      uc2Kstreams: false
      uc2Flink: false
      uc2BeamFlink: false
      uc2BeamSamza: false
      uc3LoadGenerator: false
      uc3Kstreams: false
      uc3Flink: false
      uc3BeamFlink: false
      uc3BeamSamza: false
      uc4LoadGenerator: false
      uc4Kstreams: false
      uc4Flink: false
      uc4BeamFlink: false
      uc4BeamSamza: false
    benchmarks:
      uc1Kstreams: false
      uc1Flink: false
      uc1BeamFlink: false
      uc1BeamSamza: false
      uc2Kstreams: false
      uc2Flink: false
      uc2BeamFlink: false
      uc2BeamSamza: false
      uc3Kstreams: false
      uc3Flink: false
      uc3BeamFlink: false
      uc3BeamSamza: false
      uc4Kstreams: false
      uc4Flink: false
      uc4BeamFlink: false
      uc4BeamSamza: false
###
# Prometheus Monitoring Stack (Prometheus Operator)
###
kube-prometheus-stack:
  nodeSelector:
    kubernetes.io/hostname: kind-worker4
  global:
    rbac:
      create: false # enable for full-stack monitoring
  
  grafana:
    defaultDashboardsEnabled: false
    nodeSelector:
      kubernetes.io/hostname: kind-worker
  prometheusOperator:
    admissionWebhooks:
      nodeSelector:
          kubernetes.io/hostname: kind-worker4
      deployment:
        nodeSelector:
          kubernetes.io/hostname: kind-worker4
    nodeSelector:
      kubernetes.io/hostname: kind-worker4
  kubelet:
    enabled: false
  
  kubeDns:
    enabled: false
   
  kubeStateMetrics:
    enabled: false
    nodeSelector:
      kubernetes.io/hostname: kind-worker
  
  nodeExporter:
    enabled: false
  
  prometheus:
    enabled: false # Use built-in Prometheus
    nodeSelector:
      kubernetes.io/hostname: kind-worker4
prometheus: 
  enabled: true # Use built-in Prometheus
  nodeSelector:
      kubernetes.io/hostname: kind-worker4
